name: "Rate Joke Action"
description: "Rates a joke using OpenRouter, Gemini or Groq"

inputs:
  joke:
    description: "The joke to be rated"
    required: true  

outputs:
  result:
    description: "AI-generated joke evaluation"

runs:
  using: node24
  main: dist/index.js